services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.simple
    container_name: portfolio-frontend-simple
    restart: unless-stopped
    ports:
      - "8080:80"
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
