services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: portfolio-frontend
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: portfolio-api
    ports:
      - "3000:3000"
    volumes:
      - ./backend/config/master.key:/rails/config/master.key:ro
    environment:
      - RAILS_ENV=production
      - BINDING=0.0.0.0
      - CORS_ORIGINS=*
      - DATABASE_URL=postgresql://portfolio_user:portfolio_pass@portfolio-db:5432/portfolio
    networks:
      - portfolio-network
    depends_on:
      - postgres

  postgres:
    image: postgres:17
    container_name: portfolio-db
    restart: always
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: portfolio_user
      POSTGRES_PASSWORD: portfolio_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge

volumes:
  postgres_data:
    name: portfolio_postgres_data